name: Site API IaC Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'site/iac/**'
jobs:
  build-iac:
    runs-on: ubuntu-latest

    steps:
      - name: Begin Deployment...
        uses: actions/checkout@v2

      - name: Use Node 20
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Build
        run: yarn site:build:iac
        env:
          CI: true
          REPO_OWNER: ${{ secrets.REPO_OWNER }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
          REPO_BRANCH: ${{ secrets.REPO_BRANCH }}
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-session-name: LeadAdvisorHireCallingDeploy

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ secrets.AWS_STACK_NAME }}
          template: site-dist/iac/index.yml
          capabilities: CAPABILITY_NAMED_IAM
          parameter-overrides: >-
            HostedZoneId=${{ secrets.HOSTEDZONEID }}
